name: Generate ProtoBuf Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Generator Repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install Protobuf Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install Go Protobuf Tools
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.33.0
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0

      - name: Clone Proto Files Repository
        run: |
          git clone https://github.com/yukinetzy/user-service-protos.git

      - name: Generate Go Code from Proto Files
        run: |
          export PATH="$PATH:$(go env GOPATH)/bin"

          echo "Proto files:"
          find user-service-protos -name "*.proto"

          mkdir -p userpb

          protoc -I=user-service-protos \
            --go_out=. --go_opt=paths=source_relative \
            --go-grpc_out=. --go-grpc_opt=paths=source_relative \
            user-service-protos/user.proto

          echo "Generated files:"
          find . -name "*.pb.go"

          if [ -z "$(find . -name '*.pb.go')" ]; then
            echo "Error: No .pb.go files generated."
            exit 1
          fi

      - name: Commit and Push Generated Code
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "yukinetzy"
          git config --global user.email "meliodasusai@gmail.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit. Skipping commit and push."
          else
            git commit -m "Regenerate proto Go files"
            git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/yukinetzy/user-service-gen.git
            git push origin main
          fi
